jobs:
 - include:
   - language: python
     python: "2.7"
     install:
       - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
       - export PATH="$HOME/.cargo/bin:$PATH"
       - rustc -V
       - ./linux_build_py2.sh
       - pip install -e .
     scropt: 
      - python -m unittest
   - language: python
     python: "3.7"
     install:
       - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
       - export PATH="$HOME/.cargo/bin:$PATH"
       - rustc -V
       - ./linux_build_py3.sh
       - pip install -e .
     scropt: 
      - python -m unittest
   - language: rust
     script:
      - cargo test --features python2
      - cargo test --features python3

