jobs:
  - include:
    - language: python
      python: "3.7"
      # Ensure we hae rust available
      install:
        - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
        - export PATH="$HOME/.cargo/bin:$PATH"
        - rustc -V
        - ./linux_build_py3.sh
        - pip install -d .
      scropt: python -m unittest
    - language: rust
      script:
        - cargo test --feature python2
        - cargo test --feature python3

